apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/invoker-iam-disabled: "true"
    run.googleapis.com/urls: '["https://vp-api-319016052566.asia-southeast1.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-southeast1
    run.googleapis.com/satisfiesPzs: "true"
  name: vp-api
  namespace: "319016052566"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 548.0.0
        run.googleapis.com/cloudsql-instances: shosta-ai:asia-southeast1:videodb
        run.googleapis.com/network-interfaces: '[{"network":"default","subnetwork":"default"}]'
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/vpc-access-egress: private-ranges-only
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
        - command:
            - /app/api
          env:
            - name: INSTANCE_CONNECTION_NAME
              value: shosta-ai:asia-southeast1:videodb
            - name: DB_NAME
              value: video_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: db-password
            - name: REDIS_ADDR
              value: 10.104.9.251:6379
            - name: GCS_BUCKET_NAME
              value: video_store_6969f
          image: gcr.io/shosta-ai/vp-api
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          name: vp-api
          ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            tcpSocket:
              port: 8080
            timeoutSeconds: 240
      serviceAccountName: 319016052566-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
